// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo8.3.800_480

#ifndef _DEMO8_3_800_480_UI_H
#define _DEMO8_3_800_480_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Roller1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Dropdown1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_gauge_big_hor_inv_450x99_png);    // assets/gauge_big_hor_INV_450x99.png
LV_IMG_DECLARE(ui_img_gauge_big_hor_inv_450x99_back_png);    // assets/gauge_big_hor_INV_450x99_back.png
LV_IMG_DECLARE(ui_img_gauge_big_hor_450x99_png);    // assets/gauge_big_hor_450x99.png
LV_IMG_DECLARE(ui_img_gauge_big_hor_450x99_back_png);    // assets/gauge_big_hor_450x99_back.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
