// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo8.3.800_480

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_Dropdown1,
                            "Option 1\nOption 2\nOption 3\nOption 1\nOption 2\nOption 3\nOption 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 320);
    lv_obj_set_y(ui_Dropdown1, -218);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0x1AD218), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, -995);
    lv_obj_set_y(ui_Spinner1, -19);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -363);
    lv_obj_set_y(ui_Label4, -227);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Screen 2");

    ui_AFRgauge = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_AFRgauge, &ui_img_afe_400_test_1_png);
    lv_obj_set_width(ui_AFRgauge, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_AFRgauge, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_AFRgauge, -200);
    lv_obj_set_y(ui_AFRgauge, 10);
    lv_obj_set_align(ui_AFRgauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AFRgauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AFRgauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AFRneedle = lv_img_create(ui_AFRgauge);
    lv_img_set_src(ui_AFRneedle, &ui_img_afe_needle_178x24_mep_png);
    lv_obj_set_width(ui_AFRneedle, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_AFRneedle, LV_SIZE_CONTENT);    /// 178
    lv_obj_set_x(ui_AFRneedle, 0);
    lv_obj_set_y(ui_AFRneedle, -76);
    lv_obj_set_align(ui_AFRneedle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AFRneedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AFRneedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_AFRneedle, 12, 166);
    lv_img_set_angle(ui_AFRneedle, -1000);

    ui_AfrGaugeLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_AfrGaugeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AfrGaugeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AfrGaugeLabel, -198);
    lv_obj_set_y(ui_AfrGaugeLabel, 135);
    lv_obj_set_align(ui_AfrGaugeLabel, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_AfrGaugeLabel, lv_color_hex(0x2D6732), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AfrGaugeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AfrGaugeLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
